## Numpy Basic

In [1]:
import numpy as np

In [2]:
# np.array()
arr2D = np.array([[ 0.226, -0.23 , -0.86], [0.5639, 0.2379, 0.904]])
arr2D

array([[ 0.226 , -0.23  , -0.86  ],
       [ 0.5639,  0.2379,  0.904 ]])

In [3]:
# type provide
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [4]:
np.array([1, 2, 3], dtype=str)

array(['1', '2', '3'], dtype='<U1')

In [5]:
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [6]:
# create ndarrays
listData = [6, 7.5, 8, 0, 1]
arr = np.array(listData)
type(arr)

numpy.ndarray

In [7]:
# .ndim
ndList = [[1, 2, 3, 4], [5, 6, 7, 8]]
ndArray = np.array(ndList)
print(ndArray.ndim, 'dimension array')

2 dimension array


In [8]:
# .shape
ndList = [[1, 2, 3, 4], [5, 6, 7, 8]]
ndArray = np.array(ndList)
ndArray.shape

(2, 4)

In [9]:
ndArray.dtype

dtype('int64')

In [10]:
# create range data by .arange()
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[1], arr[2], arr[3:10]

(1, 2, array([3, 4, 5, 6, 7, 8, 9]))

In [12]:
# update val
arr[1:5] = 10
arr

array([ 0, 10, 10, 10, 10,  5,  6,  7,  8,  9])