## Matrices Basic

In [1]:
import numpy as np
import torch

### Creating Matrices

In [2]:
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [3]:
# convert to numpy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [4]:
# convert to pytorch tensor
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

### Creating Matrices with Default Values

In [5]:
# numpy
np.ones([2, 2]) # 2x2

array([[1., 1.],
       [1., 1.]])

In [6]:
# pytorch
torch.ones([2, 2]) # 2x2

tensor([[1., 1.],
        [1., 1.]])

In [7]:
# numpy random
np.random.rand(2, 2)

array([[0.21613525, 0.19796297],
       [0.02080324, 0.43584187]])

In [8]:
# torch random
torch.rand(2, 2)

tensor([[0.2912, 0.1769],
        [0.3889, 0.1536]])

### Seed for Reproducibility

In [9]:
# seed for GPU is different
if torch.cuda.is_available():
    print('GPU available')
    torch.cuda.manual_seed_all(0)

In [10]:
# numpy seed 
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [11]:
# random values are same if seed same
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [12]:
# no seed
np.random.rand(2, 2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [13]:
# no seed
np.random.rand(2, 2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [14]:
# pytorch seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [15]:
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [16]:
torch.rand(2, 2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])